/** Zähler room/space options for the Mieterauszug page — order matches the spec. */
export const MOVE_OUT_ROOM_OPTIONS = [
    'Wohnzimmer',
    'Schlafzimmer',
    'Kinderzimmer',
    'Gästezimmer',
    'Arbeitszimmer / Büro',
    'Esszimmer',
    'Hobbyraum (wenn beheizt und wohnlich ausgebaut)',
    'Küche',
    'Bad / Badezimmer',
    'Duschbad',
    'Gäste-WC',
    'Hauswirtschaftsraum',
    'Abstellraum (innen)',
    'Flur / Diele / Korridor',
    'Garderobe',
    'Speisekammer / Vorratskammer',
    'Kellerraum',
    'Waschraum / Trockenraum',
    'Fahrradraum',
    'Heizungsraum',
    'Technikraum',
    'Dachboden (ausgebaut oder unausgebaut)',
    'Abstellraum im Treppenhaus',
    'Garage',
    'Carport',
    'Balkon',
    'Terrasse',
    'Dachterrasse',
    'Loggia',
    'Wintergarten (beheizt = voll, unbeheizt = anteilig)',
    'Gartenanteil (bei Sondernutzung)',
] as const;
